spring.application.name=be-uri
server.port: 9001


#DB Details
spring.datasource.url: jdbc:mysql://localhost:3306/uri_db
spring.datasource.username: root
spring.datasource.password: Miku@750478


#Hiberanate Properties
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show-sql: false

#JWT details
jwt.secret: 9zK8vL2mP7qR4tX6wY8uJ0iO3pL5nB7vC9xZ1aS3dF5gH7jK9mN2pQ4rT6uV8wX0yZ
jwt.expiration: 86400000


file.upload-dir=/home/manoranjan/files
application.name=uri